name: Collect All Iran IPs

on:
  schedule:
    - cron: '0 6 * * 1'  # هر دوشنبه ساعت 6 صبح UTC
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run collector
        run: |
          python collect_all_iran_ips.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iran-ip-lists
          path: output/
          retention-days: 90
