name: Collect Iranian IPs

on:
  workflow_dispatch:     # برای اجرای دستی
  schedule:
    - cron: '0 3 * * *'  # هر روز ساعت ۳ صبح UTC

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run collector script
        run: |
          python collect_all_ir_ips.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ir_ips.txt
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update IR IP list [$(date -u +'%Y-%m-%d %H:%M:%S UTC')]"
            git push
          fi
